version: 2
updates:
  - package-ecosystem: pub
    directory: /app
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 5
    groups:
      flutter-development-dependencies:
        dependency-type: development

  - package-ecosystem: pip
    directory: /ml
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 5
    groups:
      ml-python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 5
    groups:
      backend-python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Manila
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
